services:
  - type: web
    name: earchive7
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render-java/jdk
